### ISSUE TITLE
Error when adding  kubic.asc to Ubuntu 22.04 jammy

### ISSUE THREAD

**Issue by vdveldet** [systemli/ansible-role-apt_repositories#46]
When executing the playbook below
```
- hosts: all
  become: true
  tasks:
  - name: install Podman
    vars:
      apt_repositories:
        - preset: kubic
    ansible.builtin.include_role: 
       name: systemli.apt_repositories

```
It fails with this message below

```
{"after": [], "before": [], "changed": true, "fp": "4D64390375060AA4", "id": "4D64390375060AA4", "key_id": "4D64390375060AA4", "msg": "apt-key did not return an error, but failed to add the key (check that the id is correct and *not* a subkey)", "short_id": "75060AA4"}

```
